import type {
  Citizen,
  Constituencies,
  Representative,
  Bill,
  SpendingItem,
  BudgetActual,
  AgendaItem,
  ManifestoPromise,
  Comment,
  Notification,
  TrustDataSource,
  ForumAgendaItem,
} from './types'

// ─── Constituencies ───────────────────────────────────────────────────────────

export const CONSTITUENCIES: Constituencies = {
  ward: {
    name: 'Hoodi Ward',
    body: 'BBMP',
    totalTaxPool: 42_800_000,
  },
  assembly: {
    name: 'Krishnarajapura',
    body: 'Karnataka Vidhan Sabha',
    totalTaxPool: 1_840_000_000,
  },
  lokSabha: {
    name: 'Bangalore East',
    body: 'Lok Sabha',
    totalTaxPool: 9_200_000_000,
  },
  rajyaSabha: {
    name: 'Karnataka',
    body: 'Rajya Sabha',
    totalTaxPool: 187_000_000_000,
  },
}

// ─── Citizens ─────────────────────────────────────────────────────────────────
// c1 = logged-in user (Aditya Sharma)

export const CITIZENS: Citizen[] = [
  {
    id: 'c1',
    maskedPanId: 'AXVPS****K',
    name: 'Aditya Sharma',
    annualIncome: 2_400_000,
    directTax: 426_000,
    indirectTax: 120_000,
    totalTax: 546_000,
    taxBracket: '30%',
    occupationType: 'Software Engineer',
    avatarInitials: 'AS',
    tracesVerified: true,
  },
  {
    id: 'c2',
    maskedPanId: 'BQRPM****J',
    name: 'Priya Mehta',
    annualIncome: 4_200_000,
    directTax: 1_005_000,
    indirectTax: 210_000,
    totalTax: 1_215_000,
    taxBracket: '30%',
    occupationType: 'Doctor',
    avatarInitials: 'PM',
    tracesVerified: true,
  },
  {
    id: 'c3',
    maskedPanId: 'CJKTN****R',
    name: 'Rajan Kumar',
    annualIncome: 8_500_000,
    directTax: 2_310_000,
    indirectTax: 425_000,
    totalTax: 2_735_000,
    taxBracket: '30%',
    occupationType: 'Business Owner',
    avatarInitials: 'RK',
    tracesVerified: true,
  },
  {
    id: 'c4',
    maskedPanId: 'DLWSD****N',
    name: 'Sunita Devi',
    annualIncome: 800_000,
    directTax: 37_500,
    indirectTax: 40_000,
    totalTax: 77_500,
    taxBracket: '10%',
    occupationType: 'Government Teacher',
    avatarInitials: 'SD',
    tracesVerified: true,
  },
  {
    id: 'c5',
    maskedPanId: 'EMHVP****L',
    name: 'Vikram Patel',
    annualIncome: 3_500_000,
    directTax: 795_000,
    indirectTax: 175_000,
    totalTax: 970_000,
    taxBracket: '30%',
    occupationType: 'Lawyer',
    avatarInitials: 'VP',
    tracesVerified: true,
  },
  {
    id: 'c6',
    maskedPanId: 'FNXAR****G',
    name: 'Ananya Rao',
    annualIncome: 2_800_000,
    directTax: 546_000,
    indirectTax: 140_000,
    totalTax: 686_000,
    taxBracket: '30%',
    occupationType: 'Architect',
    avatarInitials: 'AR',
    tracesVerified: true,
  },
  {
    id: 'c7',
    maskedPanId: 'GPQMS****H',
    name: 'Mohammed Siddiqui',
    annualIncome: 4_500_000,
    directTax: 1_095_000,
    indirectTax: 225_000,
    totalTax: 1_320_000,
    taxBracket: '30%',
    occupationType: 'Banker',
    avatarInitials: 'MS',
    tracesVerified: true,
  },
  {
    id: 'c8',
    maskedPanId: 'HRTLK****F',
    name: 'Lakshmi Reddy',
    annualIncome: 3_200_000,
    directTax: 696_000,
    indirectTax: 160_000,
    totalTax: 856_000,
    taxBracket: '30%',
    occupationType: 'IT Professional',
    avatarInitials: 'LR',
    tracesVerified: true,
  },
  {
    id: 'c9',
    maskedPanId: 'ISVNB****C',
    name: 'Suresh Nair',
    annualIncome: 5_500_000,
    directTax: 1_395_000,
    indirectTax: 275_000,
    totalTax: 1_670_000,
    taxBracket: '30%',
    occupationType: 'Management Consultant',
    avatarInitials: 'SN',
    tracesVerified: true,
  },
  {
    id: 'c10',
    maskedPanId: 'JYWCK****M',
    name: 'Deepa Krishnan',
    annualIncome: 1_800_000,
    directTax: 246_000,
    indirectTax: 90_000,
    totalTax: 336_000,
    taxBracket: '20%',
    occupationType: 'University Professor',
    avatarInitials: 'DK',
    tracesVerified: true,
  },
]

export const CURRENT_USER = CITIZENS[0]

// ─── Representatives ──────────────────────────────────────────────────────────

export const REPRESENTATIVES: Representative[] = [
  {
    id: 'r1',
    level: 'ward',
    name: 'Raj Kumar Singh',
    party: 'BJP',
    constituency: 'Hoodi Ward',
    constituencyBody: 'BBMP',
    constituencyTaxPool: 42_800_000,
    houseVoteWeight: 0.0023,
    elected: '2022-03-15',
    term: '2022–2027',
    photoInitials: 'RK',
    bio: 'Third-term BBMP Corporator. Former resident welfare association president. Focuses on local infrastructure and sanitation.',
  },
  {
    id: 'r2',
    level: 'assembly',
    name: 'Byramanagala Ramesh',
    party: 'INC',
    constituency: 'Krishnarajapura',
    constituencyBody: 'Karnataka Vidhan Sabha',
    constituencyTaxPool: 1_840_000_000,
    houseVoteWeight: 0.0044,
    elected: '2023-05-10',
    term: '2023–2028',
    photoInitials: 'BR',
    bio: 'First-term MLA. Former BBMP Engineer. Focuses on urban infrastructure, traffic decongestion, and youth employment.',
  },
  {
    id: 'r3',
    level: 'ls',
    name: 'C.N. Manjunath',
    party: 'BJP',
    constituency: 'Bangalore East',
    constituencyBody: 'Lok Sabha',
    constituencyTaxPool: 9_200_000_000,
    houseVoteWeight: 0.0018,
    elected: '2024-06-04',
    term: '2024–2029',
    photoInitials: 'CM',
    bio: 'Two-term MP. Former cardiologist turned politician. Serves on the Parliamentary Standing Committee on Health & Family Welfare.',
  },
  {
    id: 'r4',
    level: 'rs',
    name: 'G.C. Chandrashekar',
    party: 'INC',
    constituency: 'Karnataka',
    constituencyBody: 'Rajya Sabha',
    constituencyTaxPool: 187_000_000_000,
    houseVoteWeight: 0.0009,
    elected: '2022-04-01',
    term: '2022–2028',
    photoInitials: 'GC',
    bio: 'Rajya Sabha MP. Economist and former RBI advisor. Focuses on fiscal policy, digital infrastructure, and financial inclusion.',
  },
]

// ─── Bills ────────────────────────────────────────────────────────────────────

export const BILLS: Bill[] = [
  {
    id: 'b1',
    title: 'Ward Infrastructure Development Plan 2024–25',
    date: '2024-12-14',
    level: 'ward',
    description:
      'Annual development plan approving ₹12 Cr allocation for roads, drainage, parks, and street lighting in Hoodi Ward.',
    repVote: 'aye',
    repId: 'r1',
    ayeCount: 142,
    nayCount: 18,
    abstainCount: 4,
    result: 'passed',
  },
  {
    id: 'b2',
    title: 'BBMP Property Tax (Amendment) Resolution 2024',
    date: '2024-11-22',
    level: 'ward',
    description:
      'Resolution supporting the revised property tax guidance values for East Bengaluru wards, effective from April 2025.',
    repVote: 'aye',
    repId: 'r1',
    ayeCount: 128,
    nayCount: 42,
    abstainCount: 10,
    result: 'passed',
  },
  {
    id: 'b3',
    title: 'Karnataka Fiscal Responsibility Amendment Bill 2024',
    date: '2024-03-18',
    level: 'assembly',
    description:
      'Amends the Karnataka Fiscal Responsibility Act to raise the state borrowing ceiling by 0.5% of GSDP and create a Urban Infrastructure Fund.',
    repVote: 'aye',
    repId: 'r2',
    ayeCount: 137,
    nayCount: 85,
    abstainCount: 2,
    result: 'passed',
  },
  {
    id: 'b4',
    title: 'Karnataka Rent Control (Amendment) Bill 2024',
    date: '2024-01-30',
    level: 'assembly',
    description:
      'Proposed amendments to the Karnataka Rent Control Act to cap annual rent increases at 5% and extend tenant protection periods.',
    repVote: 'nay',
    repId: 'r2',
    ayeCount: 88,
    nayCount: 136,
    abstainCount: 0,
    result: 'failed',
  },
  {
    id: 'b5',
    title: 'Karnataka Prevention of Slaughter & Preservation of Animals Bill 2024',
    date: '2024-02-12',
    level: 'assembly',
    description:
      'Bill to amend cattle slaughter regulations and strengthen provisions for animal preservation across Karnataka.',
    repVote: 'aye',
    repId: 'r2',
    ayeCount: 141,
    nayCount: 83,
    abstainCount: 0,
    result: 'passed',
  },
  {
    id: 'b6',
    title: 'Finance Bill 2024',
    date: '2024-07-23',
    level: 'ls',
    description:
      'Union Budget finance bill implementing revised income tax slabs under the new regime, LTCG changes, and infrastructure cess.',
    repVote: 'aye',
    repId: 'r3',
    ayeCount: 293,
    nayCount: 235,
    abstainCount: 14,
    result: 'passed',
  },
  {
    id: 'b7',
    title: 'Waqf (Amendment) Bill 2024',
    date: '2024-08-08',
    level: 'ls',
    description:
      'Amends the Waqf Act 1995 to strengthen government oversight of Waqf properties, introduce digital registration, and update survey procedures.',
    repVote: 'aye',
    repId: 'r3',
    ayeCount: 288,
    nayCount: 232,
    abstainCount: 22,
    result: 'passed',
  },
  {
    id: 'b8',
    title: 'Digital Personal Data Protection Act 2023',
    date: '2023-08-11',
    level: 'ls',
    description:
      'Establishes a comprehensive framework for digital personal data protection, consent mechanisms, and the Data Protection Board of India.',
    repVote: 'aye',
    repId: 'r3',
    ayeCount: 312,
    nayCount: 88,
    abstainCount: 42,
    result: 'passed',
  },
]

// ─── Spending ─────────────────────────────────────────────────────────────────

export const SPENDING_ITEMS: SpendingItem[] = [
  {
    id: 's1',
    head: 'Roads & Infrastructure',
    pct: 28,
    amount: 12_000_000,
    accentColor: '#FF9933',
    items: [
      {
        id: 's1-1',
        name: 'Hoodi Main Road Widening (Phase 2)',
        amount: 4_200_000,
        pctOfHead: 35,
        status: 'Under Construction',
        daysInStatus: 340,
        vendor: 'KRDCL Infrastructure Ltd',
        vendorLink: '#',
        citizenRatings: { onTrack: 38, neutral: 24, stalled: 18 },
      },
      {
        id: 's1-2',
        name: 'Kacharakanahalli Flyover',
        amount: 5_800_000,
        pctOfHead: 48,
        status: 'Tendered',
        daysInStatus: 120,
        vendor: 'Tender Open — L1 evaluation pending',
        vendorLink: '#',
        citizenRatings: { onTrack: 12, neutral: 28, stalled: 8 },
      },
      {
        id: 's1-3',
        name: 'Ward Office Approach Road Repair',
        amount: 450_000,
        pctOfHead: 4,
        status: 'Completed',
        daysInStatus: 89,
        vendor: 'Srinivasa Civil Works',
        vendorLink: '#',
        citizenRatings: { onTrack: 62, neutral: 8, stalled: 3 },
      },
      {
        id: 's1-4',
        name: 'Storm Water Drain Upgrade — Sector 4',
        amount: 1_550_000,
        pctOfHead: 13,
        status: 'Stalled',
        daysInStatus: 421,
        vendor: 'BV Constructions',
        vendorLink: '#',
        citizenRatings: { onTrack: 4, neutral: 12, stalled: 72 },
      },
    ],
  },
  {
    id: 's2',
    head: 'Public Health',
    pct: 22,
    amount: 9_400_000,
    accentColor: '#D32F2F',
    items: [
      {
        id: 's2-1',
        name: 'Primary Health Centre Equipment Upgrade',
        amount: 1_200_000,
        pctOfHead: 13,
        status: 'Completed',
        daysInStatus: 95,
        vendor: 'Medline Healthcare Supplies',
        vendorLink: '#',
        citizenRatings: { onTrack: 71, neutral: 9, stalled: 4 },
      },
      {
        id: 's2-2',
        name: 'Mobile Medical Unit — Ward Coverage',
        amount: 850_000,
        pctOfHead: 9,
        status: 'Under Construction',
        daysInStatus: 210,
        vendor: 'Ashwin Vehicle Conversions',
        vendorLink: '#',
        citizenRatings: { onTrack: 22, neutral: 31, stalled: 14 },
      },
      {
        id: 's2-3',
        name: 'Maternity & Child Health Centre Upgrade',
        amount: 2_400_000,
        pctOfHead: 26,
        status: 'Allocated',
        daysInStatus: 180,
        vendor: 'Procurement in progress',
        vendorLink: '#',
        citizenRatings: { onTrack: 8, neutral: 18, stalled: 6 },
      },
      {
        id: 's2-4',
        name: 'Annual Immunisation & Polio Drive',
        amount: 450_000,
        pctOfHead: 5,
        status: 'Completed',
        daysInStatus: 30,
        vendor: 'BBMP Health Dept (Direct)',
        vendorLink: '#',
        citizenRatings: { onTrack: 88, neutral: 5, stalled: 1 },
      },
      {
        id: 's2-5',
        name: 'Dengue & Mosquito Control Programme',
        amount: 4_500_000,
        pctOfHead: 48,
        status: 'Under Construction',
        daysInStatus: 60,
        vendor: 'Karnataka State Health Dept',
        vendorLink: '#',
        citizenRatings: { onTrack: 44, neutral: 22, stalled: 18 },
      },
    ],
  },
  {
    id: 's3',
    head: 'Education',
    pct: 18,
    amount: 7_700_000,
    accentColor: '#000080',
    items: [
      {
        id: 's3-1',
        name: 'Govt. Primary School New Building — Hoodi',
        amount: 3_200_000,
        pctOfHead: 42,
        status: 'Under Construction',
        daysInStatus: 520,
        vendor: 'KSW Constructions Pvt Ltd',
        vendorLink: '#',
        citizenRatings: { onTrack: 28, neutral: 35, stalled: 42 },
      },
      {
        id: 's3-2',
        name: 'Digital Classroom Equipment — 6 Schools',
        amount: 1_800_000,
        pctOfHead: 23,
        status: 'Completed',
        daysInStatus: 75,
        vendor: 'Edutech Solutions Bangalore',
        vendorLink: '#',
        citizenRatings: { onTrack: 78, neutral: 10, stalled: 2 },
      },
      {
        id: 's3-3',
        name: 'Mid-Day Meal Programme 2023–24',
        amount: 550_000,
        pctOfHead: 7,
        status: 'Completed',
        daysInStatus: 365,
        vendor: 'BBMP Nutrition Board',
        vendorLink: '#',
        citizenRatings: { onTrack: 91, neutral: 4, stalled: 1 },
      },
      {
        id: 's3-4',
        name: 'Ward Sports Complex & Playground',
        amount: 2_150_000,
        pctOfHead: 28,
        status: 'Stalled',
        daysInStatus: 680,
        vendor: 'Sapthagiri Infrastructure',
        vendorLink: '#',
        citizenRatings: { onTrack: 3, neutral: 9, stalled: 84 },
      },
    ],
  },
  {
    id: 's4',
    head: 'Water & Sanitation',
    pct: 15,
    amount: 6_400_000,
    accentColor: '#138808',
    items: [
      {
        id: 's4-1',
        name: 'Underground Drainage Network — Phase 3',
        amount: 3_800_000,
        pctOfHead: 59,
        status: 'Under Construction',
        daysInStatus: 480,
        vendor: 'BWSSB Direct Works',
        vendorLink: '#',
        citizenRatings: { onTrack: 18, neutral: 32, stalled: 38 },
      },
      {
        id: 's4-2',
        name: 'Overhead Water Tank — Kacharakanahalli',
        amount: 1_600_000,
        pctOfHead: 25,
        status: 'Tendered',
        daysInStatus: 95,
        vendor: 'L1 yet to be awarded',
        vendorLink: '#',
        citizenRatings: { onTrack: 10, neutral: 22, stalled: 14 },
      },
      {
        id: 's4-3',
        name: 'Public Toilet Blocks (6 nos.)',
        amount: 650_000,
        pctOfHead: 10,
        status: 'Completed',
        daysInStatus: 120,
        vendor: 'Swachh Bharat Mission — BBMP',
        vendorLink: '#',
        citizenRatings: { onTrack: 55, neutral: 18, stalled: 8 },
      },
      {
        id: 's4-4',
        name: 'Solid Waste Segregation Infrastructure',
        amount: 350_000,
        pctOfHead: 5,
        status: 'Completed',
        daysInStatus: 45,
        vendor: 'BBMP Solid Waste Mgmt',
        vendorLink: '#',
        citizenRatings: { onTrack: 48, neutral: 22, stalled: 12 },
      },
    ],
  },
  {
    id: 's5',
    head: 'Public Safety & Lighting',
    pct: 10,
    amount: 4_300_000,
    accentColor: '#6b7280',
    items: [
      {
        id: 's5-1',
        name: 'CCTV Surveillance Network — 48 cameras',
        amount: 1_800_000,
        pctOfHead: 42,
        status: 'Under Construction',
        daysInStatus: 240,
        vendor: 'Hikvision Authorised Integrator',
        vendorLink: '#',
        citizenRatings: { onTrack: 62, neutral: 18, stalled: 8 },
      },
      {
        id: 's5-2',
        name: 'LED Street Lighting Upgrade',
        amount: 1_300_000,
        pctOfHead: 30,
        status: 'Completed',
        daysInStatus: 180,
        vendor: 'Philips Lighting India Ltd',
        vendorLink: '#',
        citizenRatings: { onTrack: 82, neutral: 10, stalled: 3 },
      },
      {
        id: 's5-3',
        name: 'Ward Fire Safety Equipment',
        amount: 1_200_000,
        pctOfHead: 28,
        status: 'Allocated',
        daysInStatus: 150,
        vendor: 'Procurement in progress',
        vendorLink: '#',
        citizenRatings: { onTrack: 14, neutral: 28, stalled: 6 },
      },
    ],
  },
  {
    id: 's6',
    head: 'Administration & Salaries',
    pct: 7,
    amount: 3_000_000,
    accentColor: '#9ca3af',
    items: [
      {
        id: 's6-1',
        name: 'Ward Office Staff Salaries & Allowances',
        amount: 2_200_000,
        pctOfHead: 73,
        status: 'Completed',
        daysInStatus: 365,
        vendor: 'BBMP HR Division',
        vendorLink: '#',
        citizenRatings: { onTrack: 42, neutral: 24, stalled: 12 },
      },
      {
        id: 's6-2',
        name: 'IT Systems & Record Digitisation',
        amount: 500_000,
        pctOfHead: 17,
        status: 'Under Construction',
        daysInStatus: 90,
        vendor: 'NIC Karnataka',
        vendorLink: '#',
        citizenRatings: { onTrack: 38, neutral: 28, stalled: 8 },
      },
      {
        id: 's6-3',
        name: 'Ward Office Renovation',
        amount: 300_000,
        pctOfHead: 10,
        status: 'Completed',
        daysInStatus: 60,
        vendor: 'Srinivasa Civil Works',
        vendorLink: '#',
        citizenRatings: { onTrack: 28, neutral: 14, stalled: 4 },
      },
    ],
  },
]

// ─── Budget vs Actuals ────────────────────────────────────────────────────────

export const BUDGET_ACTUALS: BudgetActual[] = [
  { id: 'ba1', head: 'Roads & Infrastructure', budgeted: 12_000_000, actual: 10_820_000, accentColor: '#FF9933' },
  { id: 'ba2', head: 'Public Health',          budgeted:  9_400_000, actual: 10_110_000, accentColor: '#D32F2F' },
  { id: 'ba3', head: 'Education',              budgeted:  7_700_000, actual:  7_595_000, accentColor: '#000080' },
  { id: 'ba4', head: 'Water & Sanitation',     budgeted:  6_400_000, actual:  7_190_000, accentColor: '#138808' },
  { id: 'ba5', head: 'Public Safety',          budgeted:  4_300_000, actual:  4_010_000, accentColor: '#6b7280' },
  { id: 'ba6', head: 'Administration',         budgeted:  3_000_000, actual:  3_095_000, accentColor: '#9ca3af' },
]

// ─── Agenda Items ─────────────────────────────────────────────────────────────

export const AGENDA_ITEMS: AgendaItem[] = [
  {
    id: 'ag1',
    title: 'Install speed bumps and pedestrian crossings on Hoodi Gate Road',
    description:
      'Three accident-prone stretches near the school zone and market area need immediate traffic calming measures.',
    raisedBy: 'AXVPS****K',
    level: 'ward',
    cumulativeWeightedVote: 4_820_000,
  },
  {
    id: 'ag2',
    title: 'Build community centre with library in Kacharakanahalli Layout',
    description:
      'Layout has no common meeting space. Propose a 2,000 sq ft multi-purpose hall with a small reading room.',
    raisedBy: 'BQRPM****J',
    level: 'ward',
    cumulativeWeightedVote: 3_210_000,
  },
  {
    id: 'ag3',
    title: 'Plant 500 trees and install benches along ITPL Main Road median',
    description:
      'The 3 km stretch has no shade. A green median with seating will reduce heat island effect and improve walkability.',
    raisedBy: 'FNXAR****G',
    level: 'ward',
    cumulativeWeightedVote: 2_640_000,
  },
  {
    id: 'ag4',
    title: 'Set up anganwadi centre in Srinivasa Nagar sub-locality',
    description:
      'Nearest anganwadi is 2.4 km away. 180+ children in the sub-locality are underserved.',
    raisedBy: 'DLWSD****N',
    level: 'assembly',
    cumulativeWeightedVote: 18_400_000,
  },
  {
    id: 'ag5',
    title: 'Increase BMTC bus frequency on KR Puram–Mahadevapura Route 313K',
    description:
      'Current headway is 35 minutes at peak hours. Request reduction to 12 minutes and addition of 4 buses.',
    raisedBy: 'HRTLK****F',
    level: 'assembly',
    cumulativeWeightedVote: 12_800_000,
  },
]

// ─── Manifesto Promises ───────────────────────────────────────────────────────

export const MANIFESTO_PROMISES: ManifestoPromise[] = [
  {
    id: 'mp1',
    repId: 'r2',
    promise: 'Construct two flyovers to reduce traffic congestion at KR Puram and Mahadevapura junctions',
    status: 'allocated',
    evidence: 'DPR approved by BDA in Oct 2024. Land acquisition underway. Construction expected Q3 2025.',
    citizenVerifications: { delivered: 4, partial: 18, not: 22 },
  },
  {
    id: 'mp2',
    repId: 'r2',
    promise: 'Upgrade all 45 government schools in constituency with smart boards and computer labs',
    status: 'partial',
    evidence: '22 of 45 schools completed. Remaining 23 schools in progress — pending ₹2.4 Cr state grant release.',
    citizenVerifications: { delivered: 28, partial: 54, not: 12 },
  },
  {
    id: 'mp3',
    repId: 'r2',
    promise: 'Provide free public Wi-Fi at 50 locations including bus stops, parks, and markets',
    status: 'delivered',
    evidence: '52 hotspots live as of January 2024. Managed by BSNL. Average uptime 94%.',
    citizenVerifications: { delivered: 112, partial: 22, not: 8 },
  },
  {
    id: 'mp4',
    repId: 'r2',
    promise: 'Ensure 24x7 piped water supply to all 28,000 households in constituency',
    status: 'not',
    evidence: 'BWSSB confirms average daily supply of 8–10 hours. UGD Phase 3 pipeline incomplete.',
    citizenVerifications: { delivered: 6, partial: 24, not: 138 },
  },
  {
    id: 'mp5',
    repId: 'r2',
    promise: 'Build a new BMTC bus depot at KR Puram to improve east Bengaluru bus operations',
    status: 'allocated',
    evidence: 'Land identified near KR Puram railway station. BMTC board approved in Feb 2024. Tender pending.',
    citizenVerifications: { delivered: 2, partial: 14, not: 28 },
  },
  {
    id: 'mp6',
    repId: 'r2',
    promise: 'Conduct monthly health camps for senior citizens in every ward',
    status: 'delivered',
    evidence: 'Health camps running since June 2023. 9,800+ seniors covered across 14 wards. Verified by PHC records.',
    citizenVerifications: { delivered: 98, partial: 18, not: 4 },
  },
  {
    id: 'mp7',
    repId: 'r2',
    promise: 'Install 500 additional street lights in dark stretches across the constituency',
    status: 'delivered',
    evidence: '523 LED lights installed by Dec 2023. Location data on BBMP StreetLight portal.',
    citizenVerifications: { delivered: 88, partial: 14, not: 6 },
  },
  {
    id: 'mp8',
    repId: 'r2',
    promise: 'Set up a skill development and vocational training centre for unemployed youth',
    status: 'partial',
    evidence: 'Centre opened at KR Puram in Aug 2024 with 3 trade courses. 8 more courses promised but not started.',
    citizenVerifications: { delivered: 24, partial: 62, not: 18 },
  },
]

// ─── Comments (seed data for Agenda threads) ──────────────────────────────────

export const SEED_COMMENTS: Record<string, Comment[]> = {
  ag1: [
    {
      id: 'cmt1',
      maskedPanId: 'CJKTN****R',
      name: 'Rajan Kumar',
      avatarInitials: 'RK',
      taxContribution: 2_735_000,
      text: 'My kids go to school on this road. Three accidents last month alone. This is long overdue — please prioritise the stretch near GEAR School first.',
      weightedUpvotes: 74_800,
      timestamp: '2024-11-12T09:14:00Z',
    },
    {
      id: 'cmt2',
      maskedPanId: 'EMHVP****L',
      name: 'Vikram Patel',
      avatarInitials: 'VP',
      taxContribution: 970_000,
      text: 'Speed bumps alone won\'t help unless the street lights are also fixed. Combination of both would be far more effective.',
      weightedUpvotes: 41_200,
      timestamp: '2024-11-13T14:22:00Z',
    },
    {
      id: 'cmt3',
      maskedPanId: 'DLWSD****N',
      name: 'Sunita Devi',
      avatarInitials: 'SD',
      taxContribution: 77_500,
      text: 'As a resident near the market, I fully support this. The junction near Hoodi Gate is especially dangerous in the morning rush.',
      weightedUpvotes: 8_200,
      timestamp: '2024-11-14T08:55:00Z',
    },
  ],
  ag2: [
    {
      id: 'cmt4',
      maskedPanId: 'GPQMS****H',
      name: 'Mohammed Siddiqui',
      avatarInitials: 'MS',
      taxContribution: 1_320_000,
      text: 'A community centre is exactly what the layout needs. Also request a small amphitheatre for cultural events.',
      weightedUpvotes: 28_400,
      timestamp: '2024-11-08T11:30:00Z',
    },
    {
      id: 'cmt5',
      maskedPanId: 'ISVNB****C',
      name: 'Suresh Nair',
      avatarInitials: 'SN',
      taxContribution: 1_670_000,
      text: 'Good idea but please ensure disabled access and proper ventilation. Previous BBMP buildings have been poor quality.',
      weightedUpvotes: 22_100,
      timestamp: '2024-11-09T16:45:00Z',
    },
  ],
  ag3: [
    {
      id: 'cmt6',
      maskedPanId: 'HRTLK****F',
      name: 'Lakshmi Reddy',
      avatarInitials: 'LR',
      taxContribution: 856_000,
      text: 'The median trees are a great idea. Would also suggest native species like neem and peepal that require minimal maintenance.',
      weightedUpvotes: 18_600,
      timestamp: '2024-11-05T10:20:00Z',
    },
  ],
}

// ─── Notifications ────────────────────────────────────────────────────────────

export const NOTIFICATIONS: Notification[] = [
  {
    id: 'n1',
    type: 'bill',
    read: false,
    timestamp: '2024-08-08T14:30:00Z',
    title: 'Your MP voted on Waqf (Amendment) Bill',
    description: 'C.N. Manjunath voted AYE. Bill passed 288–232. Your constituency vote weight: 0.0059%.',
    targetTab: '/bills',
  },
  {
    id: 'n2',
    type: 'status',
    read: false,
    timestamp: '2024-10-22T09:15:00Z',
    title: 'Project status change: Hoodi Main Road Widening',
    description: 'Status updated from Tendered → Under Construction. Contractor: KRDCL Infrastructure Ltd.',
    targetTab: '/spending',
  },
  {
    id: 'n3',
    type: 'agenda',
    read: true,
    timestamp: '2024-11-12T08:00:00Z',
    title: 'New ward agenda item raised',
    description: '"Install speed bumps on Hoodi Gate Road" raised by AXVPS****K. 24 citizens have backed it.',
    targetTab: '/agenda',
  },
  {
    id: 'n4',
    type: 'bill',
    read: true,
    timestamp: '2024-07-23T17:00:00Z',
    title: 'Finance Bill 2024 passed in Lok Sabha',
    description: 'C.N. Manjunath voted AYE. New income tax slabs effective FY 2024–25.',
    targetTab: '/bills',
  },
  {
    id: 'n5',
    type: 'agenda',
    read: true,
    timestamp: '2024-11-01T11:00:00Z',
    title: 'New assembly agenda item',
    description: '"Increase BMTC bus frequency on Route 313K" — 48 citizens backing with 12.8M weighted votes.',
    targetTab: '/agenda',
  },
]

// ─── Trust chain ──────────────────────────────────────────────────────────────

export const TRUST_DATA_SOURCES: TrustDataSource[] = [
  {
    name: 'TRACES',
    description: 'Tax Credit & Reconciliation Analysis and Correction Enabling System',
    owner: 'Income Tax Department, Govt of India',
    url: 'https://www.tdscpc.gov.in',
    usage: 'Digital cryptographic signature on every citizen tax record',
  },
  {
    name: 'Aadhaar / UIDAI',
    description: 'Biometric identity verification API',
    owner: 'Unique Identification Authority of India',
    url: 'https://uidai.gov.in',
    usage: 'Anchors every citizen record to verified biometric identity — prevents duplicates',
  },
  {
    name: 'GSTN',
    description: 'GST Network — indirect tax data',
    owner: 'Ministry of Finance, Govt of India',
    url: 'https://www.gst.gov.in',
    usage: 'Provides indirect tax (GST) contribution data for vote weight calculation',
  },
  {
    name: 'CAG',
    description: 'Comptroller & Auditor General annual audit reports',
    owner: 'CAG of India',
    url: 'https://cag.gov.in',
    usage: 'Annual audit of total constituency tax pool figures — external verification',
  },
  {
    name: 'IT Dept PAN Registry',
    description: 'Active PAN count published annually',
    owner: 'Income Tax Department',
    url: 'https://incometax.gov.in',
    usage: 'Cross-verifies total citizen count on platform against official active PAN count',
  },
  {
    name: 'Finance Ministry',
    description: 'Union Budget and expenditure data portal',
    owner: 'Ministry of Finance',
    url: 'https://www.indiabudget.gov.in',
    usage: 'Verifies constituency-level tax pool totals and spending allocation figures',
  },
]

export const TAMPER_PROOF_MECHANISMS = [
  'TRACES cryptographic signature on every citizen tax record',
  'Sum of all citizen vote weights must equal exactly 100% of constituency pool',
  'Total citizen count cross-verified against IT Department active PAN count',
  'Constituency pool totals matched against CAG and Finance Ministry publications',
  'Every data point is RTI-verifiable — citizens can file RTI for any figure',
  'Read-only architecture — platform stores zero identity data',
  'Open-source smart contract audit trail for vote weight calculations',
]

// ─── Citizen Forum (aggregated from all citizens' token allocations) ──────────

export const FORUM_AGENDA: ForumAgendaItem[] = [
  {
    id: 'f1',
    title: 'Speed bumps and pedestrian safety on Hoodi Gate Road',
    description:
      'Top priority across all tax brackets. School zone safety is the single most consistent demand from ward citizens.',
    level: 'ward',
    aggregatedTokens: 3_240,
    topRaisedBy: 'Multiple citizens',
  },
  {
    id: 'f2',
    title: 'Complete the stalled Sports Complex construction',
    description:
      '680+ days stalled. Citizens demand accountability from contractor and BBMP. High weighted-vote support across income groups.',
    level: 'ward',
    aggregatedTokens: 2_810,
    topRaisedBy: 'Multiple citizens',
  },
  {
    id: 'f3',
    title: 'Upgrade UGD drainage to prevent flooding in Sector 4',
    description:
      'Storm water drain stalled for 421 days. Annual monsoon flooding disrupts 1,200+ households.',
    level: 'ward',
    aggregatedTokens: 2_450,
    topRaisedBy: 'Multiple citizens',
  },
  {
    id: 'f4',
    title: 'Ensure 24x7 water supply — MLA manifesto promise unfulfilled',
    description:
      'Only 8–10 hours supply daily vs manifesto promise of 24x7. Citizens demand accountability.',
    level: 'assembly',
    aggregatedTokens: 2_180,
    topRaisedBy: 'Multiple citizens',
  },
  {
    id: 'f5',
    title: 'Set up anganwadi in Srinivasa Nagar',
    description:
      '180+ children underserved. Nearest centre is 2.4 km away. Strong support from lower income brackets.',
    level: 'assembly',
    aggregatedTokens: 1_920,
    topRaisedBy: 'Multiple citizens',
  },
  {
    id: 'f6',
    title: 'Fly over construction — KR Puram junction',
    description: 'Traffic congestion at KR Puram junction is the worst in the constituency. DPR approved but work not started.',
    level: 'assembly',
    aggregatedTokens: 1_680,
    topRaisedBy: 'Multiple citizens',
  },
]

// ─── Default token allocations for logged-in user ────────────────────────────

export const DEFAULT_TOKEN_ALLOCATIONS: Record<string, number> = {
  ag1: 30,
  ag2: 20,
  ag3: 15,
  ag4: 25,
  ag5: 10,
}

// ─── Utility: compute vote weights ───────────────────────────────────────────

export function computeVoteWeights(totalTax: number) {
  return {
    ward:     (totalTax / CONSTITUENCIES.ward.totalTaxPool)     * 100,
    assembly: (totalTax / CONSTITUENCIES.assembly.totalTaxPool) * 100,
    lokSabha: (totalTax / CONSTITUENCIES.lokSabha.totalTaxPool) * 100,
  }
}

export function computeRatingWeight(totalTax: number): number {
  return Math.max(1, Math.round(totalTax / 100_000))
}

export function formatCurrency(amount: number, compact = false): string {
  if (compact) {
    if (amount >= 10_000_000) return `₹${(amount / 10_000_000).toFixed(2)} Cr`
    if (amount >= 100_000)    return `₹${(amount / 100_000).toFixed(2)} L`
    return `₹${amount.toLocaleString('en-IN')}`
  }
  return `₹${amount.toLocaleString('en-IN')}`
}
